# Generated by Django 4.1rc1 on 2022-08-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsApp', '0003_alter_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_title',
            field=models.CharField(max_length=255),
        ),
    ]
